<?php


//ehostrtoupperThisisseuredoumentusingspeialpaperandinksPleaseholdituptothelighttoverifythet
//thewordBARAZALAMITIHANIandtheORIGINALembeddedthreadanbeseenthroughthepaper
//NotValidwithoutahologram

echo strtoupper("







ModellingistheprocessofrepresentingamodelwhichincludesitsconstructionandworkingThismodelissimilartoarealsystemwhichhelpstheanalystpredicttheeffectofchangestothesystemInotherwordsmodellingiscreatingamodelwhichrepresentsasystemincludingtheirpropertiesItisanactofbuildingamodel
SimulationofasystemistheoperationofamodelintermsoftimeorspacewhichhelpsanalyzetheperformanceofanexistingoraproposedsystemInotherwordssimulationistheprocessofusingamodeltostudytheperformanceofasystemItisanactofusingamodelforsimulation
ModellingAndSimulationApplicationAreasModellingandSimulationcanbeappliedtothefollowingareasMilitaryapplicationstrainingandsupportdesigningsemiconductorstelecommunicationscivilengineeringdesignsandpresentationsandEbusinessmodels








");

?>